import json

notebook = {
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Comparaison des dynamiques Swendsen-Wang (100% CuPy Optimisé)\n",
    "\n",
    "Ce notebook implémente et compare trois dynamiques de clusters pour la détection de communautés sur un graphe signé (modèle de Sankararaman-Baccelli) comme décrit dans le Chapitre 11 de la thèse.\n",
    "\n",
    "Les trois dynamiques sont :\n",
    "- **SW-edges classique** : dynamique arête par arête.\n",
    "- **SW-triangles (blancs)** : l'énergie des arêtes est transférée uniquement aux triangles orientés vers le haut.\n",
    "- **SW-triangles (half-half)** : l'énergie de chaque arête est divisée en deux et partagée entre ses deux triangles adjacents (blanc et noir)."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "!pip install cupy-cuda12x # A ajuster selon l'environnement si ce n'est pas sur Colab\n",
    "import cupy as cp\n",
    "import numpy as np\n",
    "import matplotlib.pyplot as plt\n",
    "from cupyx.scipy.sparse import csr_matrix\n",
    "from cupyx.scipy.sparse.csgraph import connected_components\n",
    "from tqdm.notebook import tqdm\n",
    "\n",
    "# Paramètres\n",
    "d = 2\n",
    "p = 0.65\n",
    "n = 10000\n",
    "L = int(np.round(n ** (1/d)))\n",
    "T = 1000\n",
    "N_samples = 10"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "def generate_graph(L):\n",
    "    N = L * L\n",
    "    edges = []\n",
    "    for y in range(L):\n",
    "        for x in range(L):\n",
    "            edges.append([y*L + x, y*L + (x+1)%L])\n",
    "    for y in range(L):\n",
    "        for x in range(L):\n",
    "            edges.append([y*L + x, ((y+1)%L)*L + x])\n",
    "    for y in range(L):\n",
    "        for x in range(L):\n",
    "            edges.append([y*L + x, ((y+1)%L)*L + (x+1)%L])\n",
    "            \n",
    "    edges = cp.array(edges)\n",
    "    \n",
    "    white_triangles = []\n",
    "    black_triangles = []\n",
    "    for y in range(L):\n",
    "        for x in range(L):\n",
    "            idx = y*L + x\n",
    "            h_edge = idx\n",
    "            v_edge = N + y*L + (x+1)%L\n",
    "            d_edge = 2*N + idx\n",
    "            white_triangles.append([h_edge, v_edge, d_edge])\n",
    "            \n",
    "            v_edge_b = N + idx\n",
    "            h_edge_b = ((y+1)%L)*L + x\n",
    "            d_edge_b = 2*N + idx\n",
    "            black_triangles.append([v_edge_b, h_edge_b, d_edge_b])\n",
    "            \n",
    "    return edges, cp.array(white_triangles), cp.array(black_triangles)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "def SW_step(sigma, W, edges, mode, up, triangles_A, triangles_B=None):\n",
    "    frozen = cp.zeros(len(edges), dtype=bool)\n",
    "    satisfied = (W * sigma[edges[:,0]] * sigma[edges[:,1]]) > 0\n",
    "    \n",
    "    if mode == 'edges':\n",
    "        freeze_prob = 1 - cp.exp(-up)\n",
    "        frozen = satisfied & (cp.random.rand(len(edges)) < freeze_prob)\n",
    "    else:\n",
    "        if mode == 'white':\n",
    "            triangles = triangles_A\n",
    "            au = 1 - cp.exp(-2 * up)\n",
    "        else:\n",
    "            triangles = cp.vstack((triangles_A, triangles_B))\n",
    "            au = 1 - cp.exp(-up)\n",
    "            \n",
    "        W_tri = W[triangles]\n",
    "        type_A = cp.prod(W_tri, axis=1) > 0\n",
    "        sat_tri = satisfied[triangles]\n",
    "        sat_count = cp.sum(sat_tri, axis=1)\n",
    "        \n",
    "        rand_vals = cp.random.rand(len(triangles))\n",
    "        freeze_A = type_A & (sat_count == 3) & (rand_vals < au)\n",
    "        freeze_B = (~type_A) & (sat_count == 2) & (rand_vals < au)\n",
    "        \n",
    "        if cp.any(freeze_A):\n",
    "            frozen[triangles[freeze_A].flatten()] = True\n",
    "            \n",
    "        # Freeze B: Sans utiliser sort(axis=1) qui détruit les perfs GPU\n",
    "        B_idx = cp.where(freeze_B)[0]\n",
    "        if len(B_idx) > 0:\n",
    "            sat_B = sat_tri[B_idx]\n",
    "            row_idx, col_idx = cp.where(sat_B)\n",
    "            pick = cp.random.randint(0, 2, size=len(B_idx))\n",
    "            flat_idx = cp.arange(len(B_idx)) * 2 + pick\n",
    "            chosen_col = col_idx[flat_idx]\n",
    "            chosen_edges = triangles[B_idx, chosen_col]\n",
    "            frozen[chosen_edges] = True\n",
    "\n",
    "    # 100% GPU - CSR Matrix optimisée\n",
    "    row = edges[frozen, 0].astype(cp.int32)\n",
    "    col = edges[frozen, 1].astype(cp.int32)\n",
    "    data = cp.ones(len(row), dtype=cp.float32)\n",
    "    \n",
    "    N_nodes = len(sigma)\n",
    "    adj = csr_matrix((data, (row, col)), shape=(N_nodes, N_nodes))\n",
    "    n_comp, labels = connected_components(adj, directed=False)\n",
    "    \n",
    "    lcc_frac = float(cp.max(cp.bincount(labels))) / N_nodes\n",
    "    \n",
    "    # Flip optimisé GPU\n",
    "    flip = cp.random.randint(0, 2, size=n_comp) * 2 - 1\n",
    "    sigma = sigma * flip[labels]\n",
    "    \n",
    "    return sigma, lcc_frac"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "edges_gpu, white_tri_gpu, black_tri_gpu = generate_graph(L)\n",
    "up = cp.log(p / (1 - p))\n",
    "modes = ['edges', 'white', 'half-half']\n",
    "\n",
    "overlap_history = {m: np.zeros((N_samples, T)) for m in modes}\n",
    "lcc_history = {m: np.zeros((N_samples, T)) for m in modes}\n",
    "\n",
    "for sample in tqdm(range(N_samples), desc=\"Samples\"):\n",
    "    Sigma = cp.random.randint(0, 2, size=L*L) * 2 - 1\n",
    "    \n",
    "    same_comm = Sigma[edges_gpu[:,0]] == Sigma[edges_gpu[:,1]]\n",
    "    correct_obs = cp.random.rand(len(edges_gpu)) < p\n",
    "    W = cp.where(same_comm == correct_obs, up, -up)\n",
    "    \n",
    "    for mode in modes:\n",
    "        sigma = cp.random.randint(0, 2, size=L*L) * 2 - 1\n",
    "        \n",
    "        for t in range(T):\n",
    "            sigma, lcc = SW_step(sigma, W, edges_gpu, mode, up, white_tri_gpu, black_tri_gpu)\n",
    "            ov = float(cp.abs(cp.mean(sigma * Sigma)))\n",
    "            \n",
    "            overlap_history[mode][sample, t] = ov\n",
    "            lcc_history[mode][sample, t] = lcc"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(15, 5))\n",
    "\n",
    "colors = {'edges': 'blue', 'white': 'orange', 'half-half': 'green'}\n",
    "labels = {'edges': 'SW-Edges', 'white': 'SW-Triangles (Blancs)', 'half-half': 'SW-Triangles (Half-Half)'}\n",
    "\n",
    "for mode in modes:\n",
    "    mean_ov = np.mean(overlap_history[mode], axis=0)\n",
    "    std_ov = np.std(overlap_history[mode], axis=0)\n",
    "    ax1.plot(mean_ov, label=labels[mode], color=colors[mode])\n",
    "    ax1.fill_between(range(T), mean_ov - std_ov, mean_ov + std_ov, color=colors[mode], alpha=0.2)\n",
    "    \n",
    "    mean_lcc = np.mean(lcc_history[mode], axis=0)\n",
    "    std_lcc = np.std(lcc_history[mode], axis=0)\n",
    "    ax2.plot(mean_lcc, label=labels[mode], color=colors[mode])\n",
    "    ax2.fill_between(range(T), mean_lcc - std_lcc, mean_lcc + std_lcc, color=colors[mode], alpha=0.2)\n",
    "\n",
    "ax1.set_title('Overlap (Recouvrement) vs Itérations')\n",
    "ax1.set_xlabel('Itération')\n",
    "ax1.set_ylabel('Overlap moyen')\n",
    "ax1.legend()\n",
    "ax1.grid(True)\n",
    "\n",
    "ax2.set_title('Taille de la plus grande composante (LCC) vs Itérations')\n",
    "ax2.set_xlabel('Itération')\n",
    "ax2.set_ylabel('Proportion de points dans la LCC')\n",
    "ax2.legend()\n",
    "ax2.grid(True)\n",
    "\n",
    "plt.tight_layout()\n",
    "plt.show()"
   ]
  }
 ],
 "metadata": {
  "accelerator": "GPU",
  "colab": {
   "gpuType": "A100"
  },
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.10"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}

with open("SW_Dynamics_Comparison_GPU.ipynb", "w", encoding="utf-8") as f:
    json.dump(notebook, f, indent=1, ensure_ascii=False)
